NewPortfolio/Models/Article.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewPortfolio.Models
{
    public class Article
    {
        /// <summary>
        /// Id článku
        /// </summary>      
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Obsah článku
        /// </summary>
        [Required(ErrorMessage ="Vyplňte obsah")]
        [Display(Name ="Článek")]
        [StringLength(255, ErrorMessage = "Maximum znaků je 255")]
        public string Content { get; set; } = string.Empty;
        /// <summary>
        /// Titulek článku
        /// </summary>
      
        [Required(ErrorMessage ="Vyplňte titulek")]
        [Display(Name ="Titulek")]
        [StringLength(12, ErrorMessage ="Maximum znaků je 12")]
        public string? Title { get; set; } = string.Empty;
        /// <summary>
        /// Popisek článku
        /// </summary>
      
        [Required(ErrorMessage ="Vyplňte popisek článku")]
        [Display(Name ="Popis")]
        [StringLength(12, ErrorMessage = "Maximum znaků je 12")]
        public string? Description { get; set; } = string.Empty;


        /// <summary>
        /// Id uživatele
        /// </summary>
        public string? AppUserId { get; set; }


        /// <summary>
        /// Uživatel
        /// </summary>
        public AppUser? ApplicationUser { get; set; }
      
        /// <summary>
        /// Seznam příspěvků pod hlavním příspěvkem
        /// </summary>
        public virtual IEnumerable<ArticlePost>? ArticlePosts { get; set; }

        [ForeignKey("GameId")]
        public Game? Game { get; set; }

        /// <summary>
        /// Id hry
        /// </summary>
        public int? GameId { get; set; }

        [ForeignKey("GenreId")]
        public Genre? Genre { get; set; }

        public int? GenreId { get; set; }
      
    }
}

NewPortfolio/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using NewPortfolio.Data;

using NewPortfolio.Models;
using System.Linq;
using X.PagedList;


namespace NewPortfolio.Controllers
{
    /// <summary>
    /// Příspěvky uživatelům
    /// </summary>
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private IWebHostEnvironment webHostEnvironment;

        public ArticlesController(ApplicationDbContext context,
               UserManager<AppUser> userManager,
               IWebHostEnvironment webHostEnvironment
              )
        {
            _context = context;
            _userManager = userManager;
            this.webHostEnvironment = webHostEnvironment;
           
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchby, string searchfor, int? page)
        {     
            var applicationDbContex = GetAllArticles(searchby, searchfor).ToPagedList(page ?? 1, 6);
            return View(applicationDbContex);
        }


        /// <summary>
        /// Načtení příspěvků podle titulku nebo popisku klíčovým slovem nebo znakem
        /// </summary>
        /// <param name="searchby"></param>
        /// <param name="searchfor"></param>
        /// <returns></returns>
        private List<Article> GetAllArticles(string searchby, string searchfor)
        {
            if (searchby == "title" && searchfor != null)
            {
                var applicationDbContexta = _context.Article.Include(a => a.ApplicationUser)
                    .Where(s => s.Title.ToLower()
                    .Contains(searchfor.ToLower()));
                return applicationDbContexta.ToList();
            }

            if (searchby == "description" && searchfor != null)
            {
                var applicationDbContexta = _context.Article.Include(a => a.ApplicationUser)
                  
                    .Where(s => s.Description.ToLower()
                    .Contains(searchfor.ToLower()));
                return applicationDbContexta.ToList();
            }
                var applicationDbContext = _context.Article.Include(a => a.ApplicationUser);
            return applicationDbContext.ToList();
        }
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Article == null)
                 return NotFound();
            
            var article = await _context.Article
                .Include(a => a.ApplicationUser)
                .Include(c => c.ArticlePosts)
                .Include(c => c.Game)
                .Include(c => c.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
         

            if (article == null)
                return NotFound();
            

            return View(article);
        }

        [HttpGet]
        public IActionResult AddPost(int? id)
        {
            return View();
        }


        [Authorize]         
        [HttpGet]
        public IActionResult Create()
        {
               ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id");
               ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameName");
               ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "NameGenre");
            return View();
        }


        /// <summary>
        /// Vytvoření článku
        /// </summary>
        /// <param name="article"></param>
        /// <returns></returns>
        [Authorize]         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Content,Title,Description,GameId,GenreId")] CreatePostVM article)
        {

            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameName", article.GameId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "NameGenre", article.GenreId);
            var userLog = _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity!.Name);

            //Ověření, že titulek není stejný jako popisek
            if (article.Title.ToLower() == article.Description.ToLower())
            {
                ModelState.AddModelError("title", "Název titulku nesmí být stejný jako popisek");
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //Vložení článku
                    userLog.CountPost += 1;
                    var post = new Article()
                    {
                        Id = article.Id,
                        Title = article.Title,
                        Description = article.Description,
                        Content = article.Content,
                        AppUserId = userLog.Id,
                        GameId = article.GameId,
                        GenreId = article.GenreId,
                    };

                    await _context.Article!.AddAsync(post);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    throw new Exception("Vytvoření Article se nepovedlo -  CreatePostVM article");
                }
                TempData["success"] = "Článek přidán";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Article == null)
            {
                return NotFound();
            }

            var article = await _context.Article.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", article.AppUserId);
            return View(article);
        }

        [Authorize]   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Content,Title,Description,AppUserId,NickName")] Article article)
        {
            var userLog = _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity!.Name);
       
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.Users, "Id", "Id", article.AppUserId);
            return View(article);
        }


        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Article == null)
            {
                return NotFound();
            }

            var article = await _context.Article
                .Include(a => a.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }


        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Article == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Article'  is null.");
            }

            var article = await _context.Article.FindAsync(id);
            if (article != null)
            {
                _context.Article.Remove(article);
            }

            await _context.SaveChangesAsync();
            TempData["error"] = "Článek odstraněn";
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return (_context.Article?.Any(e => e.Id == id)).GetValueOrDefault();
        }



        private string UploadImage(IFormFile file)
        {
            string uniqueFileName = "ImagesThumb";

            var folderPath = Path.Combine(webHostEnvironment.WebRootPath, "ImagesThumb");
            uniqueFileName = new Guid().ToString() + "_" + file.FileName;
            var filePath = Path.Combine(folderPath, uniqueFileName);

            using (FileStream fs = System.IO.File.Create(filePath))
            {
                file.CopyTo(fs);
                file.CopyToAsync(fs);
            }
            return uniqueFileName;
        }

        
        #region API CALLS

        [HttpGet]
        public  IActionResult GetAll()
        {
            var applicationDbContext = _context.Article.Include(a => a.ApplicationUser);
            return Json(new { data = applicationDbContext });
        }

        #endregion
    }
}

NewPortfolio/Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewPortfolio.Data;
using NewPortfolio.Interfaces;
using NewPortfolio.Models;

namespace NewPortfolio.Controllers
{
   
    public class GameController : Controller
    {

        private readonly IGame _gameRepos;
        private readonly IGenre _genre;
        private readonly ApplicationDbContext _context;


        public GameController(IGame gameRepos, IGenre genre, ApplicationDbContext context)
        {
            _gameRepos = gameRepos;
            _genre = genre; 
            _context= context;
        }


        /// <summary>
        /// Vypsání všech her
        /// </summary>
        /// <returns></returns>
        public IActionResult ShowAll()
        {
            return View(_gameRepos.GetAll());
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddGame()
        {
            var game = new Game();
            ViewData["GenreId"] = new SelectList(_context.Genres,"Id", "NameGenre");
            
            return View(game);
        }


        /// <summary>
        /// Přidá hru do seznamu
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddGame(Game game)
        {

            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "NameGenre",game.GenreId);
            if (ModelState.IsValid)
            {
                await _gameRepos.Create(game);
                _gameRepos.Save(game);
                return RedirectToAction("ShowAll");
            }
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult EditGame(int id)
        {
            var game = _gameRepos.Find(id);
            return View(game);
        }

        /// <summary>
        /// Upraví hru
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditGame(Game game)
        {
            if (ModelState.IsValid)
            {
                await _gameRepos.Update(game);
                _gameRepos.Save(game);
                return RedirectToAction("ShowAll");
            }
            return View(game);
        }

        [HttpGet]
        [Authorize]
        public IActionResult DeleteGame(int id)
        {
            var game = _gameRepos.Find(id);
            return View(game);
        }

        /// <summary>
        /// Smaže daný typ hry
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult DeleteGamePost(int id)
        {
            if (id == null || id==0)
                return RedirectToAction("ShowAll");

            if (ModelState.IsValid)
            {
                _gameRepos.Delete(id);
                TempData["error"] = "Hra smazána";
                return RedirectToAction("ShowAll");
            }

            return RedirectToAction("ShowAll");
        }

        [HttpGet]
        
        public IActionResult GetArticle(int id)
        {
            return View(_gameRepos.GetArticleList(id));
        }
    }
}

NewPortfolio/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewPortfolio.Data;
using NewPortfolio.Interfaces;
using NewPortfolio.Models;

namespace NewPortfolio.Controllers
{
    public class GenreController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly IGenre _genre;

        public GenreController(IGenre genre, ApplicationDbContext context)
        {
            _genre = genre;
            _context = context;
        }

        /// <summary>
        /// Seznam žánrů
        /// </summary>
        /// <returns></returns>
        public IActionResult ViewAllGenres()
        {
            return View(_genre.GetAll());
        }



        [HttpGet]
        public IActionResult CreateGenre()
        {

            var articles = _context.Article.ToList();
            //ViewData["article"] = new SelectList(_context.Article, "Id", "Description");
            ViewData["game"] = new SelectList(_context.Games, "Id", "GameName");

            var obj=new Genre();
            return View(obj);
        }

        [HttpPost]
        public IActionResult CreateGenre(Genre genre)
        {
            ViewData["article"] = new SelectList(_context.Games, "Id", "GameName", genre.Games);
            //Ostranění mezer a zvětšení 
            genre.NameGenre=genre.NameGenre.Trim().ToUpper();

            if (ModelState.IsValid)
            {
                _genre.Create(genre);
                return RedirectToAction("ViewAllGenres");
            }  
            return View();
        }
    }
}

NewPortfolio/Views/Articles/Create.cshtml
@model CreatePostVM


@{
    ViewData["Title"] = "Vytvořit příspěvek";
}


<section class="section-index-articles">
    <div class="section-hero">

    
        <div class="row">
    <div class="col-md-4" style="top:75px">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="text-area"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
              </div>
            <div class="form-group">
                 <label asp-for="Games"></label>
                 <select asp-for="GameId"  asp-items="ViewBag.GameId">
                     <option disabled selected>--Vyberte hru--</option>
                 </select>
            
                 <label asp-for="Genres"></label>
                 <select asp-for="GenreId" asp-items="ViewBag.GenreId">
                     <option disabled selected>--Vyberte žánr--</option>
                 </select>
             </div>
            <div class="form-group">
                  <input type="submit" value="Vytvořit" class="btn-use btn-succes width-btn" />
                  <a class="btn-use btn-edit width-btn" asp-action="Index">Zpět</a>
            </div>
        </form>
    </div>
 </div>
</div>
</section>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

NewPortfolio/Views/Articles/Delete.cshtml
@model NewPortfolio.Models.Article

@{
    ViewData["Title"] = "Delete";
}

<section class="section-index">

    <div class="section-hero">
  <div>
      <div>
          <p class="p-hero"><h6 class="h6-hero">Titulek</h6> @Html.DisplayFor(model=>model.Title)</p>
          <hr />
                <p class="p-hero"><h6 class="h6-hero">Popisek</h6> @Html.DisplayFor(model=>model.Description)</p>
          <hr />
                <p class="p-hero"><h6 class="h6-hero">Obsah  </h6> @Html.DisplayFor(model=>model.Content)</p>
          <hr />
        <form asp-action="Delete">
          <input type="hidden" asp-for="Id" />
          <input type="submit" value="Smazat" class="btn-use btn-danger" /> 
          <a class="btn-use btn-edit" asp-action="Index">Zpět</a>
        </form>
      </div>
  </div>
</div>
</section>

NewPortfolio/Views/Articles/Details.cshtml
@model NewPortfolio.Models.Article



@{
    ViewData["Title"] = $"Podčlánky článku: {Model.Description}";
    }

<section class="section-index">
    <div class="section-hero">
        <div class="account-layout-content">
            <div class="account-view">
               <div class="account-img">
                    <img src="@Model.ApplicationUser.Path" width="40" height="40" />
                </div>
                <div class="account-content">
                    <div>
                        <div class="account-nickname">
                          <a asp-action="AccountView" asp-controller="Account" asp-route-id="@Model.ApplicationUser.Id"> <h6>@Html.DisplayFor(model=>model.ApplicationUser.NickName)</h6></a>
                          <p><img class="img-comment" src="/images/email.png" /></p>
                        </div>
                    </div>
                    <div class="pf">
                        <a asp-action="ViewSendCredit" asp-controller="Account" asp-route-id="@Model.AppUserId">
                          @Model.ApplicationUser.Credit
                          <img src="/images/euro.png" />
                        </a>
                    </div>

                    <div>
                        <p>Příspěvky:@Model.ApplicationUser.CountPost</p>
                        <p>Registrován:@Model.ApplicationUser.DateOfRegister.ToString("dd.M.yyyy")</p>
                    </div>
                </div>
            </div>           
            <div class="account-text">
                <div>
                    @if (Model.Game is not null )
                    {
                        <a asp-action="GetArticle" asp-controller="Game" asp-route-id="@Model.GameId" class="btn-use btn-detail">
                           @Model.Game?.GameName
                        </a>
                        
                    }
                    @if(Model.Genre is not null)
                    {
                       <a asp-action="ViewAllGenres" asp-controller="Genre" asp-route-id="@Model.GenreId" class="btn-use btn-detail">
                           @Model.Genre?.NameGenre
                       </a>
                    }
                   <hr />
                    <div>
                       @Html.DisplayFor(model => model.Content)
                    </div>
                </div>
            </div>
        </div>
        <table >
            <thead>
                
            </thead>
            <tbody>
                @foreach (var item in Model.ArticlePosts)
                {
                     <div class="div-comment">
                          <div class="div-comment-first">
                            <h5><a asp-action="AccountView" asp-controller="Account" asp-route-id="@item.AppUserId">@item.UserName</a> 
                                <a asp-action="Index"><img class="img-comment" src="/images/email.png"></a></h5>
                            <div>
                            <p>@item.DateTime</p>

                            @if (User.IsInRole("admin"))
                            {
                                <div>
                                    <a asp-action="Delete" class="btn-use btn-danger" asp-controller="ArticlePosts" asp-route-id="@item.Id"><i class="ri-chat-delete-line"></i></a>
                                </div>
                                <div>
                                    <a asp-action="Edit" class="btn-use btn-danger" asp-controller="ArticlePosts" asp-route-id="@item.Id"><i class="ri-pencil-line"></i></a>
                                </div>
                            }
                            </div>
                       </div>
                       <div>
                            @item.Post
                       </div>
                    </div>
                }
            </tbody>
        </table>
        
        <div>
            <a class="btn-use btn-edit" asp-action="Index">Zpět</a>
            <a class="btn-use btn-succes" asp-action="Create" asp-controller="ArticlePosts" asp-route-id="@Model.Id">Přidat komentář</a>
        </div>
    </div>
</section>

NewPortfolio/Views/Articles/Edit.cshtml
@model NewPortfolio.Models.Article

@{
    ViewData["Title"] = "Edit";
}



<section class="section-index">
    <div class="section-hero">
<div class="row">
    <div class="col-md-4">
               
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
           
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title"  />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                        <textarea asp-for="Content" class="text-area"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AppUserId" hidden class="control-label"></label>
                <select asp-for="AppUserId" hidden class="form-control" asp-items="ViewBag.AppUserId"></select>
                <span asp-validation-for="AppUserId" hidden class="text-danger"></span>
            </div>
         @*    <div class="form-group">
                 <label asp-for="NickName" hidden class="control-label"></label>
                 <select asp-for="NickName" hidden class="form-control" asp-items="ViewBag.AppUserId"></select>
                 <span asp-validation-for="NickName" hidden class="text-danger"></span>
             </div>*@

            <div class="form-group">
                <input type="submit" value="Uložit" class="btn-use btn-succes" />
                <a class="btn-use btn-edit" asp-action="Index">Zpět</a>
            </div>
           
        </form>
    </div>
</div>

</div>
</section>

NewPortfolio/Views/Articles/Index.cshtml
@model IEnumerable<NewPortfolio.Models.Article>
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Seznam článků";
}
<section class="section-index-articles">
    <div class="section-hero">     
        <form asp-controller="Articles" asp-action="Index" method="get">
            <div>
                <select id="inputSearch" name="searchby">
                      <option selected value="">Vyhledat podle...</option>
                      <option value="title">Titulek</option>
                      <option value="description">Popisek</option>
                  </select>
                <input name="searchfor" id="inputSearch"/>
                <button class="btn-use btn-edit" type="submit" id="inputSearch">Najít</button>
            <a class="btn-use btn-edit" type="button" asp-controller="Articles" asp-action="Index">Smazat</a>
            </div>
        </form>
        <div  class="articles">
            <table id="tblData" width="100%">
                <thead>
                    <tr class="articles-tr">
                        <th class="articles-th">
                            Popisek
                        </th>
                        <th id="hidden" class="articles-th">
                            Titulek
                        </th>
                        <th class="articles-th">
                            Vytvořil
                        </th>
                        <th id="hidden" class="articles-th-article">
                            Obsah
                        </th>
                        @if (this.Context.User.IsInRole("admin"))
                        {
                            <th class="articles-th-btn">
                           </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                    <tr class="articles-tr-down">
                         <th>
                             <a class="text-decoration" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem=>item.Description)</a>
                         </th>
                         <th id="hidden" class="articles-th">
                            @Html.DisplayFor(model=>item.Title)
                        </th>
                         <th>
                           <div class="account-view">
                               <div class="account-img">
                                  <img src="@item.ApplicationUser.Path" width="40" height="40" />
                               </div>
                               <div class="account-content">
                                   <div>
                                       <div class="account-nickname">
                                          <a asp-action="AccountView" asp-controller="Account" asp-route-id="@item.ApplicationUser.Id"><h6>@item.ApplicationUser.NickName</h6></a>
                                          <p><img class="img-comment" src="/images/email.png" /></p>
                                       </div>
                                   </div>
                                   <div class="pf">
                                       <a asp-action="ViewSendCredit" asp-controller="Account" asp-route-id="@item.AppUserId">@item.ApplicationUser.Credit
                                         <img src="/images/euro.png" />
                                       </a>
                                   </div>
                                   <div>
                                      <p>Příspěvky:@item.ApplicationUser.CountPost</p>
                                       <p>Registrován:@item.ApplicationUser.DateOfRegister.ToString("dd.M.yyyy")</p>
                                   </div>
                               </div>
                           </div>
                        </th>
                            <th id="hidden">
                            @Html.DisplayFor(modelItem=>item.Content)
                        </th>
               
                        @if (this.Context.User.IsInRole("admin"))
                        {
                         <th id="btn-hidden" class="nav-list-button">
                           <a class="btn-use btn-danger width-btn" asp-action="Delete" asp-route-id="@item.Id"><i class="ri-chat-delete-line"></i></a>
                           <a class="btn-use btn-edit width-btn" asp-action="Edit" asp-route-id="@item.Id"><i class="ri-pencil-line"></i></a>
                         </th>
                        }
                    </tr>
                    }
               </tbody>
               </table>
            <a class="btn-use btn-succes" asp-action="Create"> <i class="ri-file-add-line"></i> Vytvořit nový</a>
            <a asp-action="Index" asp-controller="Home" class="btn-use btn-edit width-btn"> <i class="ri-home-line"></i> Domů</a>
        </div>
       <div class="pagination">
           @Html.PagedListPager((IPagedList) Model, page => Url.Action("Index", new {page,
           searchfor = Context.Request.Query["searchfor"], searchby = Context.Request.Query["searchby"]}),
           new X.PagedList.Web.Common.PagedListRenderOptions {
               LiElementClasses = new string [] {"page-item"},
               PageClasses = new string [] {"page-link"}
           })
       </div>
    </div>
</section>