NewPortfolio/Models/BuildPost.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewPortfolio.Models
{
    public class BuildPost
    {

        /// <summary>
        /// Id příspěvku k sestavení postavy
        /// </summary>
        [Key]
        public int Id {get; set; }


        /// <summary>
        /// Sestavení postavy - název třídy postavy
        /// </summary>
        [Display(Name ="Zadej třídu")]
        public string BuildName { get; set; }

        public virtual IEnumerable<Build>? Builds { get; set; }
    }
}

NewPortfolio/Controllers/BuildPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewPortfolio.Data;
using NewPortfolio.Models;

namespace NewPortfolio.Controllers
{
    
    public class BuildPostsController : Controller
    {

      
        private readonly ApplicationDbContext _context;

        public BuildPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
              return _context.BuildPosts != null ? 
                          View(await _context.BuildPosts.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.BuildPosts'  is null.");
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {


           
            if (id == null || _context.Builds == null)
            {
                return NotFound();
            }

            var buildPost = await _context.Builds
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildPost == null)
            {
                return NotFound();
            }

            return View(buildPost);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BuildPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BuildName")] BuildPost buildPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(buildPost);
                await _context.SaveChangesAsync();
                TempData["success"] = $"Build {buildPost.BuildName} přidán";
                return RedirectToAction(nameof(Index));
            }

            ModelState.Clear();
            return View(buildPost);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BuildPosts == null)
            {
                return NotFound();
            }

            var buildPost = await _context.BuildPosts.FindAsync(id);
            if (buildPost == null)
            {
                return NotFound();
            }
            return View(buildPost);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BuildName")] BuildPost buildPost)
        {
            if (id != buildPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buildPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildPostExists(buildPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(buildPost);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BuildPosts == null)
            {
                return NotFound();
            }

            var buildPost = await _context.BuildPosts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildPost == null)
            {
                return NotFound();
            }

            return View(buildPost);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BuildPosts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BuildPosts'  is null.");
            }
            var buildPost = await _context.BuildPosts.FindAsync(id);
            if (buildPost != null)
            {
                _context.BuildPosts.Remove(buildPost);
                await _context.SaveChangesAsync();
                TempData["error"] = $"Build {buildPost.BuildName} smazán";
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool BuildPostExists(int id)
        {
          return (_context.BuildPosts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

NewPortfolio/Controllers/BuildsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewPortfolio.Data;
using NewPortfolio.Models;

namespace NewPortfolio.Controllers
{
    public class BuildsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BuildsController(ApplicationDbContext context)
        {
            _context = context;
        }


        [AllowAnonymous]
        public async Task<IActionResult> Index(int? id)
        {
            var applicationDbContext = _context.Builds.Where(c=>c.BuildPostId == id).ToListAsync();
            return View(await applicationDbContext);
        }


        [AllowAnonymous]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Builds == null)
            {
                return NotFound();
            }

            var build = await _context.Builds
                .Include(b => b.BuildPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (build == null)
            {
                return NotFound();
            }

            return View(build);
        }

       [Authorize]
        public IActionResult Create()
        {
            ViewData["BuildPostId"] = new SelectList(_context.BuildPosts, "Id", "BuildName");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,BuildPostId")] Build build)
        {
            if (ModelState.IsValid)
            {
                _context.Add(build);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuildPostId"] = new SelectList(_context.BuildPosts, "Id", "BuildName", build.BuildPostId);
            return View(build);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Builds == null)
            {
                return NotFound();
            }

            var build = await _context.Builds.FindAsync(id);
            if (build == null)
            {
                return NotFound();
            }
            ViewData["BuildPostId"] = new SelectList(_context.BuildPosts, "Id", "Id", build.BuildPostId);
            return View(build);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,BuildPostId")] Build build)
        {
            if (id != build.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(build);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildExists(build.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuildPostId"] = new SelectList(_context.BuildPosts, "Id", "Id", build.BuildPostId);
            return View(build);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Builds == null)
            {
                return NotFound();
            }

            var build = await _context.Builds
                .Include(b => b.BuildPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (build == null)
            {
                return NotFound();
            }

            return View(build);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Builds == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Builds'  is null.");
            }
            var build = await _context.Builds.FindAsync(id);
            if (build != null)
            {
                _context.Builds.Remove(build);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuildExists(int id)
        {
          return (_context.Builds?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

NewPortfolio/Views/BuildPosts/Create.cshtml
@model NewPortfolio.Models.BuildPost

@{
    ViewData["Title"] = "Create";
}
<section class="section-index-articles">
    <div class="section-hero">
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BuildName" class="control-label"></label>
                <input asp-for="BuildName" class="form-control" />
                <span asp-validation-for="BuildName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Vytvořit" class="btn-use btn-succes width-btn" />
                <a asp-action="Index" class="btn-use btn-edit width-btn">Zpět</a>
            </div>
        </form>
    </div>

</div>



</div>
</section>

NewPortfolio/Views/BuildPosts/Delete.cshtml
@model NewPortfolio.Models.BuildPost

@{
    ViewData["Title"] = "Delete";
}
<section class="section-index-articles">
    <div class="section-hero">


<h3>Opravdu smazat tento build?</h3>
<div>   
    <hr />
    <dl class="row">
       <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BuildName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BuildName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Smazat" class="btn-use btn-danger" /> 
        <a asp-action="Index" class="btn-use btn-edit">Zpět</a>
    </form>
</div>
</div>
</section>

NewPortfolio/Views/BuildPosts/Details.cshtml
@model IEnumerable<Build> 

@{
    ViewData["Title"] = "Details";
}
<section class="section-index-articles">
    <div class="section-hero">


      
    <a asp-action="Index">Back to List</a>
</div>

</section>

NewPortfolio/Views/BuildPosts/Edit.cshtml
@model NewPortfolio.Models.BuildPost

@{
    ViewData["Title"] = "Editace postavy";
}
<section class="section-index-articles">
    <div class="section-hero">
<h3>Editovat</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BuildName" class="control-label"></label>
                <input asp-for="BuildName" class="form-control" />
                <span asp-validation-for="BuildName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Uložit" class="btn-use btn-edit" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn-use btn-edit">Zpět</a>
</div>

</div>
</section>

NewPortfolio/Views/BuildPosts/Index.cshtml
@model IEnumerable<NewPortfolio.Models.BuildPost>



@{
    ViewData["Title"] = "Návody";
}
<section class="section-index-articles">
    <div class="section-hero">

<h3>Zde můžete tvořit návody do her, poznatky, buildy..</h3>
<p>
    <a asp-action="Create" class="btn-use btn-succes">Vytvořit sekci návodů</a>
</p>
<table class="table">
    <thead>
                <tr class="articles-tr">
            <th colspan="2">
                Sekce
            </th>
        
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
                    <tr class="articles-tr-down" >
            <td>
                <a asp-controller="Builds" asp-action="Index" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.BuildName)</a>
            </td>
                @if(User.IsInRole("admin")){
            <td width="10%">
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn-use btn-danger"><i class="ri-chat-delete-line"></i></a>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn-use btn-edit"><i class="ri-pencil-line"></i></a>
            </td>
                }
        </tr>
     }
    </tbody>
</table>
<a asp-action="Index" asp-controller="Home" class="btn-use btn-edit">Domů</a>
</div>
</section>