NewPortfolio/Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewPortfolio.Data;
using NewPortfolio.Interfaces;
using NewPortfolio.Models;

namespace NewPortfolio.Controllers
{
   
    public class GameController : Controller
    {

        private readonly IGame _gameRepos;
        private readonly IGenre _genre;
        private readonly ApplicationDbContext _context;


        public GameController(IGame gameRepos, IGenre genre, ApplicationDbContext context)
        {
            _gameRepos = gameRepos;
            _genre = genre; 
            _context= context;
        }


        /// <summary>
        /// Vypsání všech her
        /// </summary>
        /// <returns></returns>
        public IActionResult ShowAll()
        {
            return View(_gameRepos.GetAll());
        }

        [Authorize]
        [HttpGet]
        public IActionResult AddGame()
        {
            var game = new Game();
            ViewData["GenreId"] = new SelectList(_context.Genres,"Id", "NameGenre");
            
            return View(game);
        }


        /// <summary>
        /// Přidá hru do seznamu
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddGame(Game game)
        {

            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "NameGenre",game.GenreId);
            if (ModelState.IsValid)
            {
                await _gameRepos.Create(game);
                _gameRepos.Save(game);
                return RedirectToAction("ShowAll");
            }
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult EditGame(int id)
        {
            var game = _gameRepos.Find(id);
            return View(game);
        }

        /// <summary>
        /// Upraví hru
        /// </summary>
        /// <param name="game"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditGame(Game game)
        {
            if (ModelState.IsValid)
            {
                await _gameRepos.Update(game);
                _gameRepos.Save(game);
                return RedirectToAction("ShowAll");
            }
            return View(game);
        }

        [HttpGet]
        [Authorize]
        public IActionResult DeleteGame(int id)
        {
            var game = _gameRepos.Find(id);
            return View(game);
        }

        /// <summary>
        /// Smaže daný typ hry
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public IActionResult DeleteGamePost(int id)
        {
            if (id == null || id==0)
                return RedirectToAction("ShowAll");

            if (ModelState.IsValid)
            {
                _gameRepos.Delete(id);
                TempData["error"] = "Hra smazána";
                return RedirectToAction("ShowAll");
            }

            return RedirectToAction("ShowAll");
        }

        [HttpGet]
        
        public IActionResult GetArticle(int id)
        {
            return View(_gameRepos.GetArticleList(id));
        }
    }
}

NewPortfolio/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewPortfolio.Data;
using NewPortfolio.Models;
using X.PagedList;

namespace NewPortfolio.Controllers
{
    /// <summary>
    /// Třída určená k tvoření věcí/itemů ze hry, popisy itemů/věcí
    /// </summary>
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
     
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ItemsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }


        /// <summary>
        /// Výpis věech věcí
        /// </summary>
        /// <param name="searchby"></param>
        /// <param name="searchfor"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        [AllowAnonymous]
        
        public async Task<IActionResult> Index(string searchby, string searchfor, int? page)
        {

           
            var applicationDbContex = GetAllItems(searchby, searchfor).ToPagedList(page ?? 1, 6);
            return View(applicationDbContex);           
        }
        /// <summary>
        /// Vyhledání věcí podle klíčového slova/znaku
        /// </summary>
        /// <param name="searchby"></param>
        /// <param name="searchfor"></param>
        /// <returns></returns>
        private List<Item> GetAllItems(string searchby, string searchfor)
        {
            if (searchby == "nameitem" && searchfor != null)
            {
                var applicationDbContexta = _context.Items.Include(c => c.Game).Where(s => s.NameItem.ToLower().Contains(searchfor.ToLower()));

                return  applicationDbContexta.ToList();
            }

            if (searchby == "description" && searchfor != null)
            {
                var applicationDbContexta = _context.Items.Include(c=>c.Game).Where(s => s.DescriptionItem.ToLower().Contains(searchfor.ToLower()));

                return applicationDbContexta.ToList();
            }
            var app = _context.Items.Include(c => c.Game).ToList();
            return app;    
            
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [Authorize]

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameName");
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameItem,PathItem,DescriptionItem,GameId")] Item item, IFormFile? file)
        {
            ViewData["GameId"] = new SelectList(_context.Games, "Id", "GameName", item.GameId);
            if (ModelState.IsValid)
            {

                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string itemPath = Path.Combine(wwwRootPath, @"images\Items");

                    using (var fileStream = new FileStream(Path.Combine(itemPath, fileName), FileMode.Create))
                    {
                        file.CopyToAsync(fileStream);
                    }

                    item.PathItem = @"\images\Items\" + fileName;
                    ViewData["img"] = item.PathItem;

                     await _context.Items.AddAsync(item);
                    await _context.SaveChangesAsync();
                    TempData["success"] = $"Předmět {item.NameItem} přidán";
                   return RedirectToAction(nameof(Index));
                }
            
            }
            return View(item);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameItem,PathItem")] Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw new Exception("Problém s editací - Item");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        [Authorize(Roles = "admin")]
       
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Items == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
               
                return NotFound();
            }

            return View(item);
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Items == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Items'  is null.");
            }
            var item = await _context.Items.FindAsync(id);
            if (item != null)
            {
                _context.Items.Remove(item);
                await _context.SaveChangesAsync();
                TempData["error"] = $"Předmět smazán";
                return RedirectToAction(nameof(Index));
            }
            
            return View(item);
        }

        private bool ItemExists(int id)
        {
          return (_context.Items?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

NewPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Diablo 4 LazarusWill" />
    <meta name="keywords" content="Diablo 4, LazarusWill, fórum" />
    <title>@ViewData["Title"] - LazarusWill</title>
    <link rel="shortcut icon" href="~/images/euro (1).png" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&family=Pangolin&family=Poppins:ital,wght@0,200;0,500;0,700;1,300;1,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <div>
            <a class="logo" href="">LazarusWill<small>.CZ</small></a>
            <i class="ri-youtube-line"></i>
        </div>
        <ul class="navlist">
            <li><a asp-area="" asp-controller="Home" asp-action="Index">Domů</a></li>
            <li><a asp-area="" asp-controller="Articles" asp-action="Index">Články</a></li>
            <li><a asp-area="" asp-controller="Game" asp-action="ShowAll">Hry</a></li>
            <li><a asp-area="" asp-controller="Items" asp-action="Index">Věci</a></li>
            <li><a asp-area="" asp-controller="BuildPosts" asp-action="Index">Návody</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a></li>
            <li>
              <a href="/Account/Administration">
                 @if (User.Identity.IsAuthenticated)
                 {
                     <span>Účet</span>
                 }
         
                 else
                 {
                     <span>Přihlásit</span>
                 }
              </a>
            </li>
        </ul>
        <div class="bx bx-menu" id="menu-icon"></div>
    </header>

    <main>
        <partial name="_Notification" />
        @RenderBody()
    </main>
    <footer>
        <div>
            &copy; @DateTime.Now.Year LazarusWill.cz <a asp-area="" asp-controller="Home" asp-action="RegisterAgree"> Pravidla</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NewPortfolio/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
       toastr.success('@TempData["success"]');
    </script>

}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

@*@(TempData["info"]!=null)
{
      <script src="~/lib/jquery/dist/jquery.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
      <script type="text/javascript">
          toastr.info('@TempData["info"]');
      </script>
}
@(TempData["warning"] != null)
{
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script type="text/javascript">
    toastr.warning('@TempData["warning"]');
</script>
}*@


            
    
             